---
roles: []
collections:
  - name: nephelaiio.libvirt
    source: .
    type: dir
  - name: nephelaiio.plugins
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: community.crypto
