---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: libvirt-${MOLECULE_SCENARIO_NAME}-01
    image: "${MOLECULE_KVM_IMAGE}"
  - name: libvirt-${MOLECULE_SCENARIO_NAME}-02
    image: "${MOLECULE_KVM_IMAGE}"
  - name: libvirt-${MOLECULE_SCENARIO_NAME}-03
    groups:
      - molecule_pxe
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    hosts:
      all:
        vars:
          libvirt_platforms: "{{ molecule_yml.platforms }}"
verifier:
  name: ansible
scenario:
  create_sequence:
    - create
  prepare_sequence:
    - prepare
  converge_sequence:
    - converge
  destroy_sequence:
    - destroy
  cleanup_sequence:
    - cleanup
  test_sequence:
    - dependency
    - create
    - prepare
    - verify
    - destroy
