---
- name: Delegate to legacy molecule provisioner
  ansible.builtin.import_playbook: nephelaiio.libvirt.legacy.create
  when:
    - molecule_yml is defined
    - _platforms in molecule_yml
  vars:
    _platforms: "platforms"
