---
- name: Set host facts
  ansible.builtin.import_playbook: nephelaiio.libvirt.defaults

- name: Prepare guest nodes
  ansible.builtin.import_playbook: nephelaiio.libvirt.prepare

- name: Destroy KVM guests
  hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: Debug vardefs
      ansible.builtin.debug:
        msg: "{{ _varnames | zip(_varvalues) | map('join', '=') | reject('match', '^_libvirt_network_.*$') }}"
      vars:
        _varnames: "{{ lookup('ansible.builtin.varnames', '^_libvirt_.*$', wantlist=True) }}"
        _varvalues: "{{ lookup('ansible.builtin.vars', *_varnames) }}"

    - name: Query active KVM guests
      ansible.builtin.command: "virsh -c qemu:///system list --name --state-running"
      register: _libvirt_guest_query_active
      become: "{{ _libvirt_become | bool }}"
      changed_when: false

    - name: List active KVM guests
      ansible.builtin.set_fact:
        _libvirt_guest_list_active: "{{ libvirt_platforms | map(attribute='name') | intersect(_libvirt_guest_names) }}"
      vars:
        _libvirt_guest_names: "{{ _libvirt_guest_query_active.stdout_lines | map('trim') | list }}"

    - name: Stop KVM guests
      ansible.builtin.command: "virsh -c qemu:///system destroy {{ item }}"
      become: "{{ _libvirt_become | bool }}"
      loop: "{{ _libvirt_guest_list_active }}"

    - name: Query all KVM guests
      ansible.builtin.command: "virsh -c qemu:///system list --all --name"
      register: _libvirt_guest_query_all
      become: "{{ _libvirt_become | bool }}"
      changed_when: false

    - name: List all KVM guests
      ansible.builtin.set_fact:
        _libvirt_guest_list_all: "{{ libvirt_platforms | map(attribute='name') | intersect(_libvirt_guest_names_all) }}"
      vars:
        _libvirt_guest_names_all: "{{ _libvirt_guest_query_all.stdout_lines | map('trim') | list }}"

    - name: Undefine inactive KVM guests
      ansible.builtin.command: "virsh -c qemu:///system undefine {{ item }}"
      become: "{{ _libvirt_become | bool }}"
      loop: "{{ _libvirt_guest_list_all }}"

    - name: Set disk location facts
      ansible.builtin.set_fact:
        _libvirt_image_paths: "{{ [_libvirt_path] | product(_basenames) | map('join', '/') }}"
      vars:
        _basenames: "{{ libvirt_platforms | map(attribute='name') | product(['img', 'iso']) | map('join', '.') }}"

    - name: Debug disk location facts
      ansible.builtin.debug:
        var: _libvirt_image_paths

    - name: Delete guest disks
      ansible.builtin.file:
        dest: "{{ item }}"
        state: absent
      loop: "{{ _libvirt_image_paths }}"

- name: Destroy KVM resources
  hosts: localhost
  vars:
    ansible_connection: local
  tasks:
    - name: Destroy KVM resources
      when: _libvirt_cleanup | bool
      block:
        - name: Verify required parameters
          ansible.builtin.assert:
            that: _libvirt_network is defined

        - name: Query active KVM networks
          ansible.builtin.command: "virsh -c qemu:///system net-list --name"
          register: _libvirt_net_query
          become: "{{ _libvirt_become | bool }}"
          changed_when: false

        - name: Destroy libvirt network
          vars:
            _libvirt_net_list: "{{ _libvirt_net_query.stdout_lines | map('trim') | list | difference(['default']) }}"
          when:
            - libvirt_purge_network | default(False) | bool
            - _libvirt_network in _libvirt_net_list
          block:
            - name: Destroy active libvirt network
              ansible.builtin.command: "virsh -c qemu:///system net-destroy {{ _libvirt_network }}"
              become: "{{ _libvirt_become | bool }}"

            - name: Query inactive KVM networks
              ansible.builtin.command: "virsh -c qemu:///system net-list --name --inactive"
              register: _libvirt_net_query
              become: "{{ _libvirt_become | bool }}"
              changed_when: false

            - name: Undefine inactive libvirt network
              ansible.builtin.command: "virsh -c qemu:///system net-undefine {{ _libvirt_network }}"
              become: "{{ _libvirt_become | bool }}"

        - name: Delete host file entries
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: ".*{{ item }}.*"
            state: absent
          loop: "{{ libvirt_platforms | map(attribute='name') }}"
          become: true

        - name: Query libvirt pools
          ansible.builtin.command: "virsh -c qemu:///system pool-list --name"
          register: _pool_query
          become: "{{ _libvirt_become | bool }}"

        - name: Delete libvirt pool
          vars:
            _libvirt_pool_list: "{{ _pool_query.stdout_lines | map('trim') | list }}"
          block:
            - name: Destroy libvirt pool
              ansible.builtin.command: "virsh -c qemu:///system pool-destroy {{ _libvirt_pool }}"
              become: "{{ _libvirt_become | bool }}"
              when: (_libvirt_pool | trim) in _libvirt_pool_list

            - name: Undefine libvirt pool
              ansible.builtin.command: "virsh -c qemu:///system pool-undefine {{ _libvirt_pool }}"
              become: "{{ _libvirt_become | bool }}"
              when: (_libvirt_pool | trim) in _libvirt_pool_list
