---
- name: Delegate to legacy provisioner
  ansible.builtin.import_playbook: nephelaiio.libvirt.legacy.prepare
  when:
    - molecule_yml is defined
    - _platforms in molecule_yml
  vars:
    _platforms: "platforms"
