---
- name: Prepare KVM host
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
  tasks:
    - name: Install deb package requirements
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - "{{ _qemu_efi }}"
          - libvirt-clients
          - libvirt-daemon-system
          - libvirt-daemon-system-systemd
        update_cache: true
      vars:
        _is_ubuntu: "{{ ansible_facts['distribution'] == 'Ubuntu' }}"
        _is_noble: "{{ ansible_facts['distribution_version'] is version('24.04', '>=') }}"
        _qemu_efi: "qemu-efi{{ '-aarch64' if (_is_ubuntu and _is_noble) else '' }}"
      when: ansible_os_family == 'Debian'

    - name: Install rpm package requirements
      ansible.builtin.package:
        name:
          - qemu-kvm
          - libvirt-client
          - libvirt-daemon
      when: ansible_os_family == 'RedHat'
