---
# Overridable values
_libvirt_hosts: "{{ libvirt_hosts | default('localhost') }}"
_libvirt_guests: "{{ libvirt_guests | default('all') }}"
_libvirt_network: "{{ libvirt_network | default('molecule') }}"
_libvirt_address: "{{ libvirt_address | default('172.31.252.1/24') }}"
_libvirt_user: "{{ libvirt_user | default(_libvirt_default_user) }}"
_libvirt_pass: "{{ libvirt_pass | default('molecule') }}"
_libvirt_pool: "{{ libvirt_pool | default(_libvirt_network) }}"
_libvirt_path: "{{ libvirt_path | default(_libvirt_default_pool_path) }}"
_libvirt_guestdir: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY', default=_libvirt_default_temp_path) }}"
_libvirt_purge: "{{ lookup('ansible.builtin.env', 'LIBVIRT_PURGE', default=False) }}"
_libvirt_logdir: "{{ lookup('ansible.builtin.env', 'MOLECULE_LOGDIR', default=_libvirt_guestdir + '/logs') }}"
_libvirt_conn_timeout: "{{ libvirt_conn_timeout | default('90') }}"

# Derived values
_libvirt_prefix: "{{ _libvirt_address | ansible.utils.ipaddr('prefix') }}"
_libvirt_iface_host: "{{ _libvirt_address | ansible.utils.ipaddr('address') }}"
_libvirt_iface_network: "{{ _libvirt_address | ansible.utils.ipaddr('network') }}"
_libvirt_iface_prefix: "{{ _libvirt_address | ansible.utils.ipaddr('prefix') }}"
_libvirt_iface_netaddr: "{{ _libvirt_iface_network }}/{{ _libvirt_iface_prefix }}"
_libvirt_network_range: "{{ _libvirt_iface_netaddr | ansible.utils.usable_range }}"
_libvirt_network_free: "{{ _libvirt_network_range.usable_ips | difference([ _libvirt_iface_network, _libvirt_iface_host]) }}"
_libvirt_network_usable: "{{ _libvirt_network_free | community.general.version_sort }}"
_libvirt_ipaddr_tpl: '{ "ipaddr": "%s" }'
_libvirt_ipaddr_data: "{{ _libvirt_network_usable[0:libvirt_platforms | length] | map(_libvirt_filter_format, _libvirt_ipaddr_tpl) }}"
_libvirt_ipaddr_list: "{{ _libvirt_ipaddr_data | map(_libvirt_filter_from_json) }}"
_libvirt_index_tpl: '{ "index": "%s" }'
_libvirt_index_data: "{{ range(libvirt_platforms | length) | map(_libvirt_filter_format, _libvirt_index_tpl) }}"
_libvirt_index_list: "{{ _libvirt_index_data | map(_libvirt_filter_from_json)  }}"
_libvirt_platform_ipaddrs: "{{ libvirt_platforms | zip(_libvirt_ipaddr_list) | map(_libvirt_filter_combine) }}"
_libvirt_platform_indices: "{{ _libvirt_platform_ipaddrs | zip(_libvirt_index_list) | map(_libvirt_filter_combine) }}"
_libvirt_platform_data: "{{ _libvirt_platform_indices }}"

# Hardcoded values
_libvirt_filter_from_json: 'ansible.builtin.from_json'
_libvirt_filter_format: 'nephelaiio.plugins.map_format'
_libvirt_filter_combine: 'ansible.builtin.combine'
_libvirt_filter_alias: 'nephelaiio.plugins.alias_keys'
_libvirt_filter_select_attributes: 'nephelaiio.plugins.select_attributes'
_libvirt_mac_prefix: '52:54:00'
_libvirt_default_user: "{{ lookup('ansible.builtin.env', 'USER', default=_libvirt_default_temp_path) }}"
_libvirt_default_pool_path: "/var/lib/libvirt/{{ _libvirt_network }}"
_libvirt_default_temp_path: "/tmp/{{ _libvirt_network }}"
