---
name: address
permissions:
  contents: read

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  address:
    name: address
    runs-on: libvirt
    strategy:
      matrix:
        os:
          - ubuntu2404
        scenario:
          - address
    env:
      MOLECULE_LOGDIR: "/tmp/logs"
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: devbox run -- make requirements ${{ matrix.os }} MOLECULE_LOGDIR=${{ env.MOLECULE_LOGDIR }} MOLECULE_SCENARIO=${{ matrix.scenario }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.os }}
          path: |
            ${{ env.MOLECULE_LOGDIR }}/*.log
          if-no-files-found: ignore
        if: always()
