---
name: libvirt

on:
  pull_request:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if galaxy.yml has been modified
        run: |
          # Get a list of all modified files in this PR
          FILES_CHANGED=$(git diff --name-only HEAD^ HEAD)
          echo "Files changed: $FILES_CHANGED"

          # Check if galaxy.yml is in the list of changed files
          if [[ $FILES_CHANGED != *"galaxy.yml"* ]]; then
            echo "Error: galaxy.yml has not been modified."
            exit 1
          fi

  libvirt:
    name: libvirt
    runs-on: libvirt
    needs: version
    strategy:
      matrix:
        include:
          - scenario: default
            image: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
          - scenario: default
            image: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
          - scenario: default
            image: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
          - scenario: default
            image: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
          - scenario: default
            image: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2
          - scenario: default
            image: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images/AlmaLinux-8-GenericCloud-latest.x86_64.qcow2
          - scenario: default
            image: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
          - scenario: default
            image: https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base.latest.x86_64.qcow2
          - scenario: default
            image: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud-Base.latest.x86_64.qcow2
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Run molecule tests
        run: make test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          LIBVIRT_DEBUG: 'false'
          MOLECULE_KVM_IMAGE: ${{ matrix.image }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
