---
name: libvirt

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        os:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004
          - debian12
          - alma9
          - rocky9
        scenario:
          - default
        include:
          - os: ubuntu2404
            scenario: address
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Install requirements
        run: devbox run -- make requirements

      - name: Build test scenario
        run: devbox run -- make ${{ matrix.os }}
        env:
          MOLECULE_LOGDIR: "/tmp/logs"
          MOLECULE_SCENARIO: ${{ matrix.scenario }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.os }}
          path: |
            /tmp/logs/*.log
          if-no-files-found: ignore
        if: always()
