---
name: libvirt

on:
  pull_request:
    branches:
      - master

jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        os:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004
          - debian12
          - alma9
          - rocky9
        scenario:
          - default
        include:
          - os: ubuntu2404
            scenario: address
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Generate devbox locale
        run: sudo locale-gen C.UTF-8

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Install requirements
        run: devbox run -- make requirements
        with:
          devbox-version: 0.13.7

      - name: Build test scenario
        run: devbox run -- make ${{ matrix.os }}
        env:
          MOLECULE_LOGDIR: "/tmp/logs"
          MOLECULE_SCENARIO: ${{ matrix.scenario }}

      - name: Run verification tests
        run: devbox run -- make verify
        env:
          MOLECULE_LOGDIR: "/tmp/logs"
          MOLECULE_SCENARIO: ${{ matrix.scenario }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.os }}
          path: |
            /tmp/logs/*.log
          if-no-files-found: ignore
        if: always()
