---
name: libvirt

on:
  pull_request:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if galaxy.yml has been modified
        run: |
          # Get a list of all modified files in this PR
          FILES_CHANGED=$(git diff --name-only HEAD^ HEAD)
          echo "Files changed: $FILES_CHANGED"

          # Check if galaxy.yml is in the list of changed files
          if [[ $FILES_CHANGED != *"galaxy.yml"* ]]; then
            echo "Error: galaxy.yml has not been modified."
            exit 1
          fi

  libvirt:
    name: libvirt
    runs-on: libvirt
    needs: version
    strategy:
      matrix:
        os:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004
          - debian12
          - alma9
          - alma8
          - rocky9
          - rocky8
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install requirements
        run: make requirements

      - name: Run molecule tests
        run: make ${{ matrix.os }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_LOGDIR: '/tmp/logs'

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.os }}
          path: |
            /tmp/logs/*.log
          if-no-files-found: ignore
        if: always()
